apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmq-username: cmFiYml0 # base64("rabbit")
  rabbitmq-password: cmFiYml0 # base64("rabbit")

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672   # AMQP (для приложений)
      name: amqp
    - port: 15672  # HTTP management UI
      name: http
  clusterIP: None   # важно для StatefulSet (headless service)
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
          - containerPort: 5672
            name: amqp
          - containerPort: 15672
            name: http
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      name: http
