apiVersion: v1
kind: Secret
metadata:
  name: hello-k8s-secret
type: Opaque
data:
  APP_SECRET: c2VjcmV0X3Rva2Vu # echo -n "secret_token" | base64
  MARIADB_ROOT_PASSWORD: cm9vdHBhc3M= # base64 'rootpass'
  MARIADB_USER_PASSWORD: dXNlcg==     # base64 'user'
  REDIS_PASSWORD: cmVkaXNwYXNz         # base64 'redispass'